workspace:
  base: /test
  path: config_owner

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}
    environment:
      - DOCUMENT_ROOT=/test/config_owner
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

pipeline:
  composer-install:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress

  composer-update-lowest:
    group: prepare-lowest
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}
    volumes:
      - /cache:/cache
    commands:
      - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  site-install:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}
    commands:
      - ./vendor/bin/run drupal:site-install

  test-grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}
    commands:
      - ./vendor/bin/grumphp run

  test-phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}
    commands:
      - ./vendor/bin/phpunit

matrix:
  COMPOSER_BOUNDARY:
    - lowest
    - highest
  PHP_VERSION:
    - 7.2-ci
    - 7.3-ci
